-- DEPRECATED LEGACY ENTRYPOINT — DO NOT EXECUTE.
--
-- Migrations in supabase/migrations are the only schema source of truth.
-- Existing projects must apply only migrations that are not yet present.
-- A fresh project must replay the migrations in filename order, then run the
-- verification scripts documented in supabase/README.md.
--
-- The pre-Phase-5 snapshot was removed from this path because it created broad
-- authenticated write policies and public content buckets. Keeping executable
-- insecure SQL here would make a fresh installation less secure than the live
-- Phase 8 schema.

-- Intentionally no executable statements.
