import { createError } from 'h3'
import type { ApiErrorResponse } from '~/types/adminActivity'

export type ApiErrorCode =
  | 'AUTH_REQUIRED'
  | 'ADMIN_REQUIRED'
  | 'VALIDATION_ERROR'
  | 'NOT_FOUND'
  | 'SLUG_CONFLICT'
  | 'FILE_TOO_LARGE'
  | 'UNSUPPORTED_FILE_TYPE'
  | 'STORAGE_ERROR'
  | 'CONFLICT'
  | 'INVALID_CREDENTIALS'
  | 'INVITATION_NOT_FOUND'
  | 'INVITATION_CONFLICT'
  | 'INVITATION_EXPIRED'
  | 'INVITATION_REVOKED'
  | 'INVITATION_ALREADY_USED'
  | 'INVITATION_EMAIL_MISMATCH'
  | 'ADMIN_ALREADY_ACTIVE'
  | 'ADMIN_INACTIVE'
  | 'ADMIN_NOT_FOUND'
  | 'SELF_DEACTIVATION_FORBIDDEN'
  | 'LAST_ACTIVE_ADMIN'
  | 'REVIEW_NOT_FOUND'
  | 'REDIRECT_NOT_FOUND'
  | 'BATCH_NOT_FOUND'
  | 'ASSET_NOT_FOUND'
  | 'TARGET_NOT_FOUND'
  | 'BASELINE_MISMATCH'
  | 'RECONCILIATION_MISMATCH'
  | 'PROVENANCE_MISMATCH'
  | 'TARGET_BASELINE_MISMATCH'
  | 'BOOTSTRAP_CONFLICT'
  | 'BOOTSTRAP_INCOMPLETE'
  | 'BOOTSTRAP_RECONCILIATION_FAILED'
  | 'ASSET_RECONCILIATION_FAILED'
  | 'ASSET_HASH_INVALID'
  | 'UNEXPECTED_TARGET_ASSET'
  | 'TARGET_VERSION_CONFLICT'
  | 'DECISION_EVIDENCE_REQUIRED'
  | 'PUBLISH_CHECKLIST_INCOMPLETE'
  | 'REDACTION_REQUIRED'
  | 'PUBLIC_TARGET_EVIDENCE_REQUIRED'
  | 'INVALID_DECISION'
  | 'INVALID_HTTP_EVIDENCE'
  | 'INVALID_DERIVATIVE'
  | 'DERIVATIVE_NOT_REQUIRED'
  | 'ORIGINAL_MISMATCH'
  | 'ACTIVE_DERIVATIVE_EXISTS'
  | 'BACKUP_EVIDENCE_REQUIRED'
  | 'CHECKPOINT_CONFLICT'
  | 'BATCH_KEY_CONFLICT'
  | 'TARGET_SET_MISMATCH'
  | 'REVIEW_NOT_RESOLVED'
  | 'TARGET_STATUS_CONFLICT'
  | 'BATCH_NOT_APPLICABLE'
  | 'BATCH_RECONCILIATION_FAILED'
  | 'ROLLBACK_NOT_ALLOWED'
  | 'ROLLBACK_TARGET_CONFLICT'
  | 'UTILITY_ROUTE_MUST_ARCHIVE'
  | 'AUDIT_APPEND_ONLY'
  | 'DRY_RUN_CANNOT_APPLY'
  | 'UNSUPPORTED_TARGET_KIND'
  | 'DERIVATIVE_OBJECT_NOT_FOUND'
  | 'INVALID_DERIVATIVE_PATH'
  | 'CONTENT_NOT_PUBLISHABLE'
  | 'MANAGED_TARGET_DELETE_FORBIDDEN'
  | 'MANAGED_TARGET_MUST_BE_UNPUBLISHED'
  | 'MANAGED_TARGET_RELEASE_REQUIRED'
  | 'ORIGINAL_ASSET_IMMUTABLE'
  | 'INTERNAL_ERROR'

export const apiError = (
  statusCode: number,
  code: ApiErrorCode,
  message: string,
  fieldErrors?: Record<string, string[]>
) => createError({
  statusCode,
  statusMessage: message,
  data: { statusCode, code, message, ...(fieldErrors ? { fieldErrors } : {}) } satisfies ApiErrorResponse
})

export const isUniqueViolation = (error: unknown) => Boolean(
  error && typeof error === 'object' && Reflect.get(error, 'code') === '23505'
)

export const internalApiError = () => apiError(500, 'INTERNAL_ERROR', 'The request could not be completed.')
